# Configure your own custom Rec Mono for Code font

#                                                                              
#                                             /$$$$$$     /$$                  
#                                            /$$    /    /  /             $$$  
#    /$$$$$$$    /$$$$$$$    /$$ $$$$$    /$$$$$$$$$   /$$$$$      /$$$$$$$ /  
#   /$$_____/   /$$____ $$  | $$$___ $$  |___ $$__/   |___ $$     /$$     $$   
#  | $$        | $$   | $$  | $$   | $$     | $$         | $$    \  $$$$$$$    
#  | $$        | $$   | $$  | $$   | $$     | $$         | $$     \  $$   /    
#  \  $$$$$$$  \  $$$$$$$   | $$   | $$   /$$$$$$$$$  /$$$$$$$$$  / $$$$$$$$   
#   \_______/   \_______/   |__/   |__/  |_________/ |_________/ | $$      $$  
#                                                                \  $$$$$$$$   
#                                                                 \_______/    
#                                                                              

# -----------------------------------------------------------------------------
# Family Name

# The name you want after "Rec Mono" in your custom fonts. 
# Example: "Custom" will yield the family "Rec Mono Custom". 
# Keep under 13 characters in length to avoid potential OS bugs.

Family Name: Sharkey 

Fonts:
  Regular:
    MONO: 1
    CASL: 1
    wght: 400
    slnt: 0
    CRSV: 0
  Italic:
    MONO: 1
    CASL: 1
    wght: 400
    slnt: -10
    CRSV: 1
  Bold:
    MONO: 1
    CASL: 1
    wght: 700
    slnt: 0
    CRSV: 0
  Bold Italic:
    MONO: 1
    CASL: 1
    wght: 700
    slnt: -10
    CRSV: 1

Code Ligatures: True

Features:
- ss01 # Single-story a
- ss03 # Simplified f
- ss04 # Simplified i
- ss05 # Simplified l
- ss06 # Simplified r
- ss07 # Simplified italic diagonals
- ss09 # Simplified 6 and 9
- ss10 # Dotted 0
- ss11 # Simplified 1
- ss12 # Simplified @
